project:
  type: website
  render: 
    - index.qmd
  output-dir: "docs"

tbl-cap-location: top
favicon: assets/icon.png
open-graph: true
  
  
website:
  title: 'Malawi | Drought Response'
  page-navigation: true
  sidebar: true
 
  navbar:
    search: true
    pinned: true
    bread-crumbs: true
    logo: "assets/logo.png"
 
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - this analysis is for demonstration purposes only."
    type: warning
    position: below-navbar

  page-footer: 
    background: primary
    foreground: white
    border: false
    center: "Copyright 2025, International Organization for Migration" 
    # right: 
    #   - icon: github
    #     href: https://github.com/
    #   - icon: link
    #     href: https://dtm.iom.int/ 


format:
  html:
    theme: [cosmo, custom.scss]
    lightbox: true
    fig-align: center
    number-sections: true
    html-table-processing: none
    self-contained: true
    code-fold: true
    echo: false
    toc: true
    warning: false
    code-overflow: wrap
    default-image-extension: svg
    smooth-scroll: true
    other-links:
      - text: Displacement Tracking Matrix
        href: https://dtm.iom.int/
      - text: IOM
        href: https://www.iom.int/
      - text: Data download (external)
        icon: file-excel
        href: index.qmd
      - text: Report download (external)
        icon: file-pdf
        href: index.qmd
  # typst: 
  #   toc: true
  #   section-numbering: 1.1.a
  #   columns: 2
  #   mainfont: "Roboto"
  #epub: default
  # revealjs: default

format-links:
  - html
  - format: typst
    text: PDF
    icon: file-pdf
  - format: epub
    text: eBook
    icon: book




