[workspace]
authors = ["Brian Mc Donald <brian@brianmcdonald.me>"]
channels = ["conda-forge"]
name = "malawi"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
jupyterlab = ">=4.4.3,<5"
polars = ">=1.30.0,<2"
lonboard = ">=0.10.4,<0.11"
matplotlib = ">=3.10.3,<4"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.6,<3"
geopandas = ">=1.1.0,<2"
fastexcel = ">=0.14.0,<0.15"
contextily = ">=1.6.2,<2"
azure-identity = ">=1.23.0,<2"
azure-storage-file-datalake = ">=12.20.0,<13"
pyarrow = ">=20.0.0,<21"

[pypi-dependencies]
lonboard = "*"
